import person from "../assets/images/person3.jpg";

export const userData = [
  {
    id: 1,
    userId: "USR1001",
    username: "Jane_Allen",
    profileImg: person,
    module: "Database Systems",
    status: "active",
    name: "Jane Allen",
    designation: "Senior Lecturer",
  },
  {
    id: 1,
    userId: "USR1001",
    username: "Jane_Allen",
    profileImg: person,
    module: "Database Systems",
    status: "active",
    name: "Jane Allen",
    designation: "Senior Lecturer",
  },
  {
    id: 1,
    userId: "USR1001",
    username: "Jane_Allen",
    profileImg: person,
    module: "Database Systems",
    status: "active",
    name: "Jane Allen",
    designation: "Senior Lecturer",
  },
  {
    id: 1,
    userId: "USR1001",
    username: "Jane_Allen",
    profileImg: person,
    module: "Database Systems",
    status: "active",
    name: "Jane Allen",
    designation: "Senior Lecturer",
  },
  {
    id: 1,
    userId: "USR1001",
    username: "Jane_Allen",
    profileImg: person,
    module: "Database Systems",
    status: "active",
    name: "Jane Allen",
    designation: "Senior Lecturer",
  },
  {
    id: 1,
    userId: "USR1001",
    username: "Jane_Allen",
    profileImg: person,
    module: "Database Systems",
    status: "active",
    name: "Jane Allen",
    designation: "Senior Lecturer",
  },
];
